Repository boostcamp-2020/Project18-D-WEB-Boostact, pull requests merged in 2020-12, with the labels that each got.

#10 [Fix] determineState의 오류 수정
  demo/index.js
  src/boostact/Boostact.js
  src/index.js
Labels: bug

#18 Feat/useEffect
  src/boostact/Boostact.js
Labels: bug, chore, hook, setting

#20 Fix/create and test page
  README.md
  example/Timer/App.js
  example/Timer/index.js
  src/boostact/Boostact.js
  src/boostactDOM/BoostactDOM.js
  src/index.js
Labels: bug, chore, documentation, hook

#31 Fix/route
  demo/About.jsx
  demo/Home.jsx
  demo/RoutingTest.jsx
  demo/Timer.jsx
  demo/funtionalComponent.jsx
  demo/index.js
  src/boostact/Boostact.js
  src/boostact/Route.js
Labels: bug, chore, hook, route

#24 [Fix] 변화가 없는데도 render되는 현상 수정 #23
  src/boostact/Boostact.js
Labels: bug

#46 [fix] useContext 버그 수정 #16
  src/boostact/Boostact.js
Labels: bug

#48 [fix] : 중복으로 render 함수 호출 시 제대로 적용이 안되는 묹제 해결
  src/boostact/Boostact.js
Labels: bug

#49 Feat/use memo
  src/boostact/Boostact.js
Labels: bug, hook

#54 [feat] 네비게이터 구현 & 헤더 구현
  demo/App.jsx
  demo/component/common/header/style.js
  demo/component/common/navContainer/navContainer.jsx
  demo/component/common/navigatorDocument/navigator.jsx
  demo/component/common/navigatorExample/navigator.jsx
Labels: chore

#56 글씨체 변경
  demo/App.jsx
  demo/index.js
Labels: chore, documentation

#59 jss 적용 병합
  demo/component/common/button/button.jsx
  demo/component/common/button/style.js
  demo/component/common/header/header.jsx
  demo/component/common/header/style.js
  demo/component/common/navContainer/navContainer.jsx
  demo/component/common/navigatorDocument/navigator.jsx
  package-lock.json
  package.json
Labels: chore

#64 Style/index page
  README.md
  demo/page/IndexPage/Banner.jsx
  demo/page/IndexPage/BoostactIndex.jsx
  demo/page/IndexPage/CodeString.jsx
  demo/page/IndexPage/Gist.jsx
  demo/page/IndexPage/SimpleContents.jsx
  demo/page/IndexPage/style.js
  demo/page/bugReport/bugReport.jsx
  demo/page/bugReport/style.js
  demo/page/example/timer/Timer.jsx
  demo/page/example/timer/style.js
  package.json
  webpack.config.js
Labels: chore, documentation, example

#74 Feat/make page
  demo/App.jsx
  demo/Router.jsx
  demo/component/common/a/style.js
  demo/component/common/footer/style.js
  demo/component/common/header/button/button.jsx
  demo/component/common/header/button/style.js
  demo/component/common/header/headDecoration.jsx
  demo/component/common/header/header.jsx
  demo/component/common/header/style.js
  demo/component/common/navContainer/list.jsx
  demo/component/common/navContainer/navContainer.jsx
  demo/component/common/navigatorDocument/navigator.jsx
  demo/component/common/navigatorExample/navigator.jsx
  demo/component/navigation/container/container.jsx
  demo/component/navigation/container/list.jsx
  demo/component/navigation/container/style.js
  demo/component/navigation/document/contents.js
  demo/component/navigation/document/navigator.jsx
  demo/component/navigation/document/style.js
  demo/component/navigation/example/contents.js
  demo/component/navigation/example/navigator.jsx
  demo/component/navigation/example/style.js
  demo/html/index.html
  demo/page/IndexPage/Banner.jsx
  demo/page/IndexPage/CodeString.jsx
  demo/page/IndexPage/SimpleContents.jsx
  demo/page/IndexPage/searchpage/content.jsx
  demo/page/IndexPage/searchpage/main.jsx
  demo/page/IndexPage/searchpage/searchbar.jsx
  demo/page/IndexPage/timer/Timer.jsx
  demo/page/IndexPage/timer/style.js
  demo/page/IndexPage/todoList/style.js
  demo/page/IndexPage/todoList/todoTemplate.jsx
  demo/page/document/document.jsx
  demo/page/document/documentRouter.jsx
  demo/page/document/index/helloWorld.jsx
  demo/page/document/index/hooksState.jsx
  demo/page/document/index/useCallback.jsx
  demo/page/document/index/useContext.jsx
  demo/page/document/index/useEffect.jsx
  demo/page/document/index/useMemo.jsx
  demo/page/document/index/useReducer.jsx
  demo/page/document/index/useState.jsx
  demo/page/document/index/virtualDom.jsx
  demo/page/document/style.js
  demo/page/example/example.jsx
  demo/page/example/style.js
  demo/styled.jsx
  package.json
  src/boostact/Boostact.js
  src/boostact/Route.js
  webpack.config.js
Labels: chore, fix, hook, route, setting, style

#82 [style] 예제 항상 가운데에 있게끔 수정하기
  demo/page/IndexPage/style.js
  demo/page/IndexPage/timer/style.js
  demo/page/IndexPage/todoList/style.js
Labels: style

#86 [feat] 문서에서 Hook 사용 가이드 만들기
  demo/component/navigation/document/contents.js
  demo/page/document/documentRouter.jsx
  demo/page/document/index/guide.jsx
Labels: documentation
